### ISSUE TITLE
Discord Key Question

### ISSUE THREAD

**Issue by ve6mad** [paradoxally/Trivia-Swift#4]
Good day,

Just a simple question. For the Discord Channels array, what is the format the app expects? Is is "serverID/channelID" or just the "channelID"? Apologies for the stupid question :)

Thanks.

**Comment by spaz926** [comment]
Discord channel ID's are unique. You only need to put the channel ID in the Config file.

**Comment by ve6mad** [comment]
Awesome, thank you for that! Appreciate it.
